version: "3"

services:
  spark-master:
    image: spark-custom
    container_name: spark-master
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./netflix_titles.csv:/opt/spark-data/netflix_titles.csv
      - ./netflix_eda.py:/opt/spark-data/netflix_eda.py
      - ./results:/opt/spark-data/results 

  spark-worker-1:
    image: spark-custom
    container_name: spark-worker-1
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./results:/opt/spark-data/results
      - ./netflix_titles.csv:/opt/spark-data/netflix_titles.csv

  spark-worker-2:
    image: spark-custom
    container_name: spark-worker-2
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./results:/opt/spark-data/results
      - ./netflix_titles.csv:/opt/spark-data/netflix_titles.csv
